package definition

const (
	ERROR_CODE_SUCCESS                              = 0  // 成功
	ERROR_CODE_FAIL                                 = 1  // 失敗<共用失敗非提供給前端使用>
	ERROR_CODE_ERROR_REQUEST_DATA                   = 2  // 參數錯誤 (參數錯誤)
	ERROR_CODE_ERROR_DATABASE                       = 3  // 資料庫錯誤 (資料庫發生錯誤，請重新嘗試或聯繫客服)
	ERROR_CODE_ERROR_NOTIFICATION                   = 4  // 外部通知錯誤 (遠端伺服器發生錯誤，請重新嘗試或聯繫客服)
	ERROR_CODE_ERROR_JWT                            = 5  // JWT認證錯誤<401錯誤不用顯示訊息>
	ERROR_CODE_ERROR_PERMISSION                     = 6  // 權限錯誤 (權限不足，請聯繫客服開通權限)
	ERROR_CODE_ERROR_CAPTCHA                        = 7  // 驗證碼錯誤 (驗證碼錯誤)
	ERROR_CODE_ERROR_ACCOUNT                        = 8  // 帳號錯誤 (帳號不存在或密碼錯誤)
	ERROR_CODE_ERROR_ACCOUNT_DISABLED               = 9  // 帳號禁用 (帳號禁用，請聯繫客服)
	ERROR_CODE_ERROR_ACCOUNT_EXIST                  = 10 // 帳號已存在
	ERROR_CODE_ERROR_LOCAL_CACHE_NOT_EXIST          = 11 // 本地端紀錄不存在
	ERROR_CODE_ERROR_TIME_RANGE                     = 12 // 時間範圍超過{0}分鐘
	ERROR_CODE_ERROR_TIME_BEFORE_DAYS               = 13 // 起始時間超過{0}天前
	ERROR_CODE_ERROR_TOP_AGENT_SETTING              = 14 // 請確認上級代理設定或聯繫上級代理
	ERROR_CODE_ERROR_REDIS                          = 15 // 資料庫錯誤 (資料庫發生錯誤，請重新嘗試或聯繫客服)
	ERROR_CODE_ERROR_NO_DATA_BE_AFFECTED            = 16 // 沒有資料被更新
	ERROR_CODE_ERROR_ACCOUNT_ROLE_USING             = 17 // 有帳號套用此角色
	ERROR_CODE_ERROR_ROLE_NAME_EXIST                = 18 // 代理角色名稱重複
	ERROR_CODE_ERROR_PERMISSION_ROLE_NOT_EXIST      = 19 // 角色權限不存在
	ERROR_CODE_ERROR_AGENT_IP_WHITELIST_COUNT       = 20 // 代理ip白名單必須至少設置一組
	ERROR_CODE_ERROR_AGENT_NAME_EXIST               = 21 // 代理名稱重複
	ERROR_CODE_ERROR_AGENT_WALLET_AMOUNT_NOT_ENOUGH = 22 // 代理錢包餘額不足
	ERROR_CODE_ERROR_DATABASE_NO_ROWS               = 23 // 資料庫查詢不到紀錄
	ERROR_CODE_ERROR_FEATURE_DISABLED               = 24 // 此功能目前未開放
	ERROR_CODE_ERROR_CHANNEL_ID                     = 25 // 無效的頻道
	ERROR_CODE_ERROR_CHAT_SEND_MESSAGE_FAILED       = 26 // 發送訊息錯誤
	ERROR_CODE_ERROR_API_SERVER_REQUEST_FAILED      = 27 // api伺服器請求失敗
	ERROR_CODE_ERROR_ACCOUNT_NOT_EXIST              = 28 // 帳號不存在
	ERROR_CODE_ERROR_QUERY_COMBITION                = 29 // 組合sql語法錯誤
	ERROR_CODE_ERROR_DATABASE_COMMIT                = 30 // 資料庫錯誤 (資料庫發生錯誤，請重新嘗試或聯繫客服)
	ERROR_CODE_ERROR_DATABASE_EXEC                  = 31 // 資料庫錯誤 (資料庫發生錯誤，請重新嘗試或聯繫客服)
	ERROR_CODE_ERROR_GAME_SERVER_NOT_IN_MAINTENANCE = 32 // 遊戲伺服器非維護中
	ERROR_CODE_ERROR_IP_FORMAT                      = 33 // IP格式錯誤
	ERROR_CODE_ERROR_GAME_USERS_NOT_EXIST           = 34 // 遊戲用戶不存在
	ERROR_CODE_ERROR_GAME_USERS_BE_BLOCK            = 35 // 遊戲用戶已被封停
	ERROR_CODE_ERROR_ANALYZE_FAILED                 = 36 // 資料解析錯誤
	ERROR_CODE_ERROR_CAPTCHA_EXPIRED                = 37 // 驗證碼過期
	ERROR_CODE_ERROR_PASSWORD_FORMAT                = 38 // 密碼格式錯誤
	ERROR_CODE_ERROR_PASSWORD                       = 39 // 密碼錯誤
	ERROR_CODE_ERROR_CONFIRM_PASSWORD               = 40 // 新密碼與確認密碼不相同
	ERROR_CODE_ERROR_PASSWORD_SAME                  = 41 // 新舊密碼相同
	ERROR_CODE_ERROR_MARQUEE_OVERDUE                = 42 // 跑馬燈逾期
	ERROR_CODE_ERROR_GAME_SERVER_IN_MAINTENANCE     = 43 // 遊戲伺服器維護中
	ERROR_CODE_ERROR_ADMIN_USER_TYPE_ILLEGAL        = 44 // 登入帳號類型錯誤(總台、代理後台帳號不可互登)
	ERROR_CODE_ERROR_ANNOUNCEMENT_NOT_EXIST         = 45 // 後台公告不存在
	ERROR_CODE_ERROR_AGENT_IP_WHITELIST             = 46 // 未加入白名單
	ERROR_CODE_ERROR_CURRENCY_NOT_SUPPORTED         = 47 // 不支援的幣種
	ERROR_CODE_ERROR_KILLRATION_PARENT_OPEN         = 48 // 總代理風控開啟中，不可修改個別風控設定
	ERROR_CODE_ERROR_WALLET_URL_PARSE_FAILED        = 49 // 單一錢包解析URL錯誤
	ERROR_CODE_ERROR_NO_CHANGE_IN_DATA              = 50 // 資料無異動
	ERROR_CODE_ERROR_INCOME_RATIO_DATA              = 51 // 遊戲風控批次資料錯誤
	ERROR_CODE_ERROR_STRING_LIMIT                   = 52 // 字數長度錯誤
	ERROR_CODE_ERROR_LOCAL                          = 99 // 本地端錯誤 (本地伺服器發生錯誤，請重新嘗試聯繫客服)
)
