ALTER TABLE "public"."permission_list"
  ADD COLUMN "action_type" int4 NOT NULL DEFAULT 0;

COMMENT ON COLUMN "public"."permission_list"."action_type" IS '操作類型';

DELETE FROM "public"."permission_list";
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100001,'檢查伺服器是否活著','/api/v1/example/health','f','test','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100100,'client取得驗證token','/api/v1/intercom/getlogintoken','t','遊戲SERVER串接使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100101,'驗證token並登入遊戲','/api/v1/intercom/logingame','t','遊戲SERVER串接使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100102,'遊戲用戶登出','/api/v1/intercom/logoutgame','t','遊戲SERVER串接使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100103,'創建每局遊戲紀錄','/api/v1/intercom/creategamerecord','t','遊戲SERVER串接使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100104,'此接口供遊戲伺服器取得跑馬燈設定列表','/api/v1/intercom/getmarqueesetting','t','遊戲SERVER串接使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100200,'創建代理帳號','/api/v1/agent/createagent','t','後台使用','t',1);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100201,'取得代理底下所有代理資料','/api/v1/agent/getagentlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100202,'秘鑰資訊顯示','/api/v1/agent/getagentsecretkey','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100203,'取得指定代理補分相關資料設定','/api/v1/agent/getagentcoinsupplyinfo','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100204,'修改指定代理補分相關資料設定','/api/v1/agent/setagentcoinsupplyinfo','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100205,'取得代理遊戲列表','/api/v1/agent/getagentgamelist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100206,'設置代理遊戲狀態','/api/v1/agent/setagentgamestate','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100207,'取得代理遊戲房間列表','/api/v1/agent/getagentgameroomlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100208,'設置代理遊戲房間狀態','/api/v1/agent/setagentgameroomstate','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100209,'取得代理權限群組權限樣板','/api/v1/agent/getagentpermissiontemplateinfo','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100210,'取得代理權限群組列表','/api/v1/agent/getagentpermissionlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100211,'創建代理權限群組','/api/v1/agent/createagentpermission','t','後台使用','t',1);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100212,'修改代理權限群組','/api/v1/agent/setagentpermission','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100213,'刪除代理權限群組','/api/v1/agent/deleteagentpermission','t','後台使用','t',3);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100214,'取得遊戲列表','/api/v1/game/getgamelist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100215,'修改遊戲狀態','/api/v1/game/setgamestate','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100216,'此接口用來重新載入本地端資料','/api/v1/global/roloadglobaldata','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100218,'取得全部代理商list(供下拉選單使用)','/api/v1/global/getagentlist','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100219,'取得全部遊戲list(供下拉選單使用)','/api/v1/global/getallgamelist','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100220,'取得上線及維護中的遊戲list(供下拉選單使用)','/api/v1/global/getgamelist','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100221,'取得房間類型list(供下拉選單使用)','/api/v1/global/getroomtypelist','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100222,'取得權限群組層級list(供下拉選單使用)','/api/v1/global/getagentpermissionlist','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100223,'用戶登錄','/api/v1/login/login','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100224,'取得驗證碼','/api/v1/login/captcha','t','後台使用','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100225,'取得目前跑馬燈設定列表','/api/v1/manage/getmarqueelist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100226,'指定取得某筆跑馬燈設定','/api/v1/manage/getmarquee','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100227,'添加跑馬燈功能','/api/v1/manage/createmarquee','t','後台使用','t',1);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100228,'編輯跑馬燈功能','/api/v1/manage/updatemarquee','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100229,'刪除跑馬燈功能','/api/v1/manage/deletemarquee','t','後台使用','t',3);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100230,'取得個人遊戲紀錄列表','/api/v1/record/getuserplayloglist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100231,'取得遊戲局記錄','/api/v1/record/getplaylogcommon','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100232,'取得帳變資料列表','/api/v1/record/getwalletledgerlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100233,'ping','/api/v1/user/ping','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100234,'取得目前已產生的有效 token list','/api/v1/user/getalivetoken','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100235,'將用戶 token 列入黑名單(主動使登入token 失效)','/api/v1/user/blacktoken','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100236,'創建後台帳號(只能創建自己的後台帳號)','/api/v1/user/createadminuser','t','後台使用','t',1);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100237,'依照查詢者角色權限列出自身權限下的子帳號列表','/api/v1/user/getadminusers','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100238,'指定查詢某後台帳號狀態','/api/v1/user/getadminuserinfo','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100239,'指定設定某後台帳號狀態','/api/v1/user/updateadminuserinfo','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100240,'依照查詢者角色權限列出遊戲會員帳號清單','/api/v1/user/getgameusers','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100241,'指定查詢某遊戲會員帳號信息','/api/v1/user/getgameuserinfo','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100242,'指定修改某遊戲會員帳號信息','/api/v1/user/updategameuserinfo','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100243,'此接口用來重新計算業績報表','/api/v1/cal/calperformancereport','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100244,'此接口用來取得當前 job 的資訊清單','/api/v1/servicestatus/getjobshedulerlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100245,'依照指定報表類型取得指定時間區段的資料','/api/v1/cal/getperformancereport','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100246,'取得代理後台IP資訊列表','/api/v1/agent/getagentipwhitelistlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100247,'取得代理後台IP資訊','/api/v1/agent/getagentipwhitelist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100248,'設置代理後台IP資訊','/api/v1/agent/setagentipwhitelist','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100249,'取得代理權限群組','/api/v1/agent/getagentpermission','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100250,'取得代理錢包餘額列表','/api/v1/agent/getagentwalletlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100251,'設置代理錢包餘額','/api/v1/agent/setagentwallet','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100252,'取得代理分數紀錄列表','/api/v1/record/getagentwalletledgerlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100253,'取得玩家錢包餘額列表','/api/v1/user/getgameuserwalletlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100254,'設置玩家錢包餘額','/api/v1/user/setgameuserwallet','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100255,'更新玩家分數紀錄狀態','/api/v1/record/confirmwalletledger','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100256,'此接口用來取得當天資訊總覽的資料','/api/v1/manage/getstatdata','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100257,'此接口用來取得今日風險玩家清單(前100名)','/api/v1/manage/getriskuserlist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100258,'此接口用來取得今日遊戲輸贏排行榜','/api/v1/manage/getgameleaderboards','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100259,'此接口用來取得chat service 連線資訊','/api/v1/notify/getchatserviceconnInfo','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100260,'此接口用來取得當前平台機率設定列表(只有管理可以使用)','/api/v1/riskcontrol/getincomeratiolist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100261,'此接口用來取得指定id平台機率設定資料(只有管理可以使用)','/api/v1/riskcontrol/getincomeratio','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100262,'此接口用來設定指定id平台機率設定資料(只有管理可以使用)','/api/v1/riskcontrol/setincomeratio','t','後台使用','t',2);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100263,'此接口用來取得最近一段時間(預設30日)的活躍玩家數&日投注人數','/api/v1/manage/getintervaldaysbettordata','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100264,'此接口用來取得今日各時段輸贏(昨日&今日)','/api/v1/manage/getintervaltotalscoredata','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100265,'此接口用來取得今日各時段(昨日&今日)','/api/v1/manage/getintervaltotalbettorinfodata','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (100266,'取得後台操作紀錄列表','/api/v1/record/getbackendactionloglist','t','後台使用','t',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (200101,'第三方遊戲API','/channel/channelHandle','t','對外串接','f',0);
INSERT INTO "public"."permission_list" ("feature_code","name","api_path","is_enabled","remark","is_required","action_type") VALUES (200102,'第三方取遊戲記錄','/record/getRecordHandle','t','對外串接','f',0);
