ALTER TABLE "public"."agent" 
  ADD COLUMN "is_not_kill_dive_cal" bool NOT NULL DEFAULT false;

COMMENT ON COLUMN "public"."agent"."is_not_kill_dive_cal" IS '計算殺放[預設]:false、不計算:true';

INSERT INTO "public"."agent" ("id", "name", "code", "secret_key", "md5_key", "commission", "info", "is_enabled", "disable_time", "update_time", "create_time", "is_top_agent", "top_agent_id", "cooperation", "coin_limit", "coin_use", "level_code", "aes_key", "member_count", "creator", "ip_whitelist", "kill_switch", "kill_ratio", "kill_info", "kill_update_time", "api_ip_whitelist", "currency", "is_not_kill_dive_cal") VALUES (5, 'test5', '26080ceb', '5cfce483c41cfb18a2ee6417e3ca9a7a', '28b0225fd10502f0', 0, '維護測試用總代理', 1, '1970-01-01 00:00:00', '2023-04-27 06:07:43.747584', '2023-04-27 06:07:43.747584', 'f', 1, 1, '0.0000', '0.0000', '00010005', 'c09216abccb73ddf', 0, 'admin', '[{"info": "台北和平辦公室", "creator": "admin", "ip_address": "192.168.180.*", "create_time": 1666592735}, {"info": "", "creator": "chouyang", "ip_address": "127.0.0.1", "create_time": 1682500677}]', 'f', '0.0000', '', '2023-04-27 06:07:43.747584', '[{"info": "桐花順服務", "creator": "admin", "ip_address": "172.30.0.152", "create_time": 1666592735}, {"info": "", "creator": "chouyang", "ip_address": "192.168.180.*", "create_time": 1688452486}]', 'VND', 't');
INSERT INTO "public"."admin_user" ("agent_id", "username", "password", "nickname", "google_auth", "google_key", "allow_ip", "account_type", "is_readonly", "is_enabled", "update_time", "create_time", "is_added", "login_time", "role", "info") VALUES (5, 'test5', 'Xh41tJ_nAYh-6kXniQX7xTo6yqtvqndqkMV0OgjWsNLocw', '維護測試用代理', 'f', '', '0.0.0.0/0', 2, 0, 1, '2023-04-27 06:07:43.747584', '2023-04-27 06:07:43.747584', 'f', '2023-04-27 06:07:43.747584', '86e72242-0c19-4229-ace4-9b1a40a26c43', '維護測試用總代理');


INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1005, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1004, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2001, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 3002, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2004, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2008, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1008, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2002, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1001, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1006, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 3001, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1002, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 4001, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1003, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2003, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 1007, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2005, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2006, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2007, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 3003, 1);
INSERT INTO "public"."agent_game" ("agent_id", "game_id", "state") VALUES (5, 2009, 1);

INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10052, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10053, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10060, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10061, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10062, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10063, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10070, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10071, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10072, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10073, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10080, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10081, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10082, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 10083, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20010, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20011, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20012, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20013, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20020, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20021, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20022, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20023, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20030, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20031, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20032, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20033, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20040, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20041, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20042, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20043, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20044, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20045, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20046, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20047, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20050, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20051, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20052, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20053, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20060, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20061, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20062, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20063, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20070, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20071, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20072, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20073, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20080, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20081, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20082, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20083, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20090, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20091, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20092, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20093, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20094, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20095, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20096, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 20097, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30010, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30011, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30012, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30013, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30020, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30021, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30022, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30030, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30031, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30032, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 30033, 1);
INSERT INTO "public"."agent_game_room" ("agent_id", "game_room_id", "state") VALUES (5, 40010, 1);

INSERT INTO "public"."agent_game_icon_list" ("agent_id", "level_code", "is_admin", "is_default", "icon_list", "update_time", "create_time") VALUES (5, '00010005', 't', 'f', '[{"hot": 0, "rank": 0, "gameId": 3003, "newest": 1}, {"hot": 1, "rank": 1, "gameId": 4001, "newest": 0}, {"hot": 1, "rank": 2, "gameId": 2008, "newest": 0}, {"hot": 0, "rank": 3, "gameId": 1008, "newest": 0}, {"hot": 0, "rank": 4, "gameId": 1001, "newest": 0}, {"hot": 0, "rank": 5, "gameId": 1002, "newest": 0}, {"hot": 0, "rank": 6, "gameId": 1003, "newest": 0}, {"hot": 0, "rank": 7, "gameId": 1004, "newest": 0}, {"hot": 0, "rank": 8, "gameId": 1005, "newest": 0}, {"hot": 0, "rank": 9, "gameId": 1006, "newest": 0}, {"hot": 0, "rank": 10, "gameId": 1007, "newest": 0}, {"hot": 0, "rank": 11, "gameId": 2001, "newest": 0}, {"hot": 0, "rank": 12, "gameId": 2002, "newest": 0}, {"hot": 0, "rank": 13, "gameId": 2003, "newest": 0}, {"hot": 0, "rank": 14, "gameId": 2004, "newest": 0}, {"hot": 0, "rank": 15, "gameId": 2005, "newest": 0}, {"hot": 0, "rank": 16, "gameId": 2006, "newest": 0}, {"hot": 0, "rank": 17, "gameId": 2007, "newest": 0}, {"hot": 0, "rank": 18, "gameId": 3001, "newest": 0}, {"hot": 0, "rank": 19, "gameId": 3002, "newest": 0}, {"hot": 0, "rank": 20, "gameId": 2009, "newest": 0}]', '2023-09-11 08:47:49.402802+00', '2023-09-08 08:48:38.012755+00');
INSERT INTO "public"."agent_custom_tag_info" ("agent_id", "level_code", "custom_tag_info", "update_time") VALUES (5, '00010005', '{"0": {"idx": 0, "info": "", "name": "", "color": ""}, "1": {"idx": 1, "info": "", "name": "", "color": ""}, "2": {"idx": 2, "info": "", "name": "", "color": ""}, "3": {"idx": 3, "info": "", "name": "", "color": ""}, "4": {"idx": 4, "info": "", "name": "", "color": ""}, "5": {"idx": 5, "info": "", "name": "", "color": ""}, "6": {"idx": 6, "info": "", "name": "", "color": ""}, "7": {"idx": 7, "info": "", "name": "", "color": ""}}', '2023-02-24 07:57:19.531051+00');