export default {
  TableDefaultLength: 10,
  TableDefaultLengthMenu: [10, 25, 50, 100],
  AccountStatus: {
    Disable: 0,
    Open: 1,
  },
  AccountType: {
    Admin: 1,
    General: 2,
    Nornam: 3,
  },
  Agent: {
    All: 0,
  },
  AgentCooperation: {
    BuyPoint: 1,
    Trust: 2,
  },
  ErrorCode: {
    Success: 0,
    Fail: 1,
    ErrorRequestData: 2,
    ErrorDatabase: 3,
    ErrorNotification: 4,
    ErrorJWT: 5,
    ErrorPermission: 6,
    ErrorCaptcha: 7,
    ErrorAccount: 8,
    ErrorAccountDisabled: 9,
    ErrorAccountExist: 10,
    ErrorLocalCacheNotExist: 11,
    ErrorTimeRange: 12,
    ErrorTimeBeforeDays: 13,
    ErrorTopAgentSetting: 14,
    ErrorRedis: 15,
    ErrorNoDataBeAffected: 16,
    ErrorAccountRoleUsing: 17,
    ErrorRoleNameExist: 18,
    ErrorPermissionRoleNotExist: 19,
    ErrorAgentIpWhitelistCount: 20,
    ErrorAgentNameExist: 21,
    ErrorAgentWalletAmountNotEnough: 22,
    ErrorDatabaseNoRows: 23,
    ErrorFeatureDisabled: 24,
    ErrorChannelId: 25,
    ErrorChatSendMessageFailed: 26,
    ErrorApiServerRequestFailed: 27,
    ErrorAccountNotExist: 28,
    ErrorQueryCombition: 29,
    ErrorDatabaseCommit: 30,
    ErrorDatabaseExec: 31,
    ErrorGameServerNotInMaintenance: 32,
    ErrorIpFormat: 33,
    ErrorGameUsersNotExist: 34,
    ErrorGameUsersBeBlock: 35,
    ErrorAnalyzeFailed: 36,
    ErrorCaptchaExoired: 37,
    ErrorPasswordFormat: 38,
    ErrorPassword: 39,
    ErrorConfirmPassword: 40,
    ErrorPasswordSame: 41,
    ErrorMarqueeOverdue: 42,
    ErrorGameServerInMaintenance: 43,
    ErrorAdminUserTypeIllegal: 44,
    ErrorAnnouncementNotExist: 45,
    ErrorAgentIpWhitelist: 46,
    ErrorCurrencyNotSupported: 47,
    ErrorKillRatioParentOpen: 48,
    ErrorWalletUrlParseFailed: 49,
    ErrorNoChangeInData: 50,
    ErrorIncomeRatioData: 51,
    ErrorStringLimit: 52,
    ErrorLocal: 99,
  },
  Game: {
    Lobby: 0,
    Friendsroom: 2,
    All: 999,
    Baccarat: 1001,
    Fantan: 1002,
    Colordisc: 1003,
    Prawncrab: 1004,
    Hundredsicbo: 1005,
    Cockfight: 1006,
    Dogracing: 1007,
    Rocket: 1008,
    Andarbahar: 1009,
    Roulette: 1010,
    Blackjack: 2001,
    Sangong: 2002,
    Bullbull: 2003,
    Texas: 2004,
    Rummy: 2005,
    Goldenflower: 2006,
    Pokdeng: 2007,
    Catte: 2008,
    Chinesepoker: 2009,
    Okey: 2010,
    Teenpatti: 2011,
    Fruitslot: 3001,
    Rcfishing: 3002,
    Plinko: 3003,
    Happyfishing: 3004,
    Fruit777slot: 4001,
    Megsharkslot: 4002,
    Midasslot: 4003,
    Wildgemslot: 4004,
    Jumphighslot: 4005,
    Pyrtreasureslot: 4006,
    Friendstexas: 5001,
  },
  GameType: {
    All: 0,
    Lobby: 0,
    BaiRen: 1,
    ChiPai: 2,
    ElectronicGame: 3,
    Slot: 4,
    FriendsRoom: 5,
  },
  GameState: {
    All: -1,
    Offline: 0,
    Online: 1,
    Maintain: 2,
  },
  RoomType: {
    All: -1,
    Newbie: 0,
    Common: 1,
    Master: 2,
    GrandMaster: 3,
    Beginner: 4,
    SmallSuccess: 5,
    GreateFacility: 6,
    Perfection: 7,
  },
  TableSortDirection: {
    Asc: 0,
    Desc: 1,
  },
  WalletLedgerKind: {
    All: 0,
    ApiUp: 1,
    ApiDown: 2,
    BackendUp: 3,
    BackendDown: 4,
    SingleWalletUp: 5,
    SingleWalletDown: 6,
  },
  MarqueeType: {
    All: 0,
    System: 1,
    Event: 2,
  },
  LangType: { All: 'All', CHS: 'zh-cn', CHT: 'zh-tw', EN: 'en-us', PT: 'pt-br', TH: 'th-th', TR: 'tr-tr', VI: 'vi-vn' },
  ActionLogType: {
    All: 0,
    Create: 1,
    Update: 2,
    Delete: 3,
  },
  AnnounceType: {
    All: 0,
    System: 1,
    Event: 2,
  },
  CurrencyType: { BRL: 'BRL', CNY: 'CNY', INR: 'INR', MYR: 'MYR', PHP: 'PHP', THB: 'THB', TRY: 'TRY', VND: 'VND' },
  AutoRiskCode: { ApiRequestLimit: 1, CoinInAndOutRatioLimit: 2, WinRateLimit: 3 },
  KillDive: {
    Normal: 0,
    ConfigKill: 1,
    BlackKill: 2,
  },
  AgentWallet: {
    Transfer: 0,
    Single: 1,
  },
  AgentLobbySwitch: {
    Normal: 1,
    FriendsRoom: 2,
  },
  Device: { All: 'all', Android: 'android', IOS: 'ios', Mac: 'mac', Other: 'other', PC: 'pc' },
  Browser: { All: 'all' },
  Country: { All: 'all' },
  CannedLanguageType: {
    Default: 0,
    Custome: 1,
  },
  CannedStatus: {
    Close: 0,
    Open: 1,
  },
  CannedEmojiType: {
    Happy: 1,
    Excited: 2,
    Calm: 3,
    Depression: 4,
    Agitated: 5,
  },
  CannedLangTypeSetting: {
    'en-us': true,
    'pt-br': true,
    'th-th': false,
    'tr-tr': true,
    'vi-vn': true,
    'zh-cn': true,
    'zh-tw': false,
  },
}
